"""Add created_at column to urls table

Revision ID: 2ea215bd299b
Revises: f01b12454fe1
Create Date: 2022-05-26 15:44:13.491980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea215bd299b'
down_revision = 'f01b12454fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE urls SET created_at = now()")
    op.alter_column('urls', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'created_at')
    # ### end Alembic commands ###
